{
  "namespace": "xtype.deployment.package.event.external.v1.data",
  "type": "record",
  "name": "PackageContentUpdateSetV1",
  "doc": "Update set content",
  "fields": [
    { "name": "name", "type": "string", "doc": "Name of the update set" },
    { "name": "sys_id", "type": "string", "doc": "sysID from ServiceNow" },
    { "name": "state", "type": "string", "doc": "State of the update set" },
    { "name": "sys_updated_by", "type": "string", "doc": "User who last updated" },
    { "name": "sys_updated_on", "type": "long", "doc": "Timestamp of last update" },
    { "name": "sys_completed_by", "type": "string", "doc": "User who completed" },
    { "name": "sys_completed_on", "type": "long", "doc": "Timestamp when completed" },
    { "name": "application", "type": ["null", "string"], "default": null, "doc": "Application identifier" },
    { "name": "application_display", "type": ["null", "string"], "default": null, "doc": "Display name of application" }
  ]
}