{
  "namespace": "xtype.deployment.package.event.external.v1.data",
  "type": "record",
  "name": "PackageContentRecordDataV1",
  "doc": "Individual record data",
  "fields": [
    { "name": "name", "type": ["null", "string"], "default": null, "doc": "Record name" },
    { "name": "sys_id", "type": ["null", "string"], "default": null, "doc": "sysID from ServiceNow" },
    { "name": "sys_scope", "type": ["null", "string"], "default": null, "doc": "System scope" },
    { "name": "sys_scope_display", "type": ["null", "string"], "default": null, "doc": "Display name of scope" },
    { "name": "table", "type": ["null", "string"], "default": null, "doc": "Table name" },
    { "name": "table_display", "type": ["null", "string"], "default": null, "doc": "Display name of table" },
    { "name": "display", "type": ["null", "string"], "default": null, "doc": "Display string" },
    { "name": "add_dependencies", "type": ["null", "boolean"], "default": null, "doc": "Add dependencies flag" }
  ]
}