{
  "namespace": "xtype.deployment.package.event.external.v1.data",
  "type": "record",
  "name": "PackageContentExecuteScriptV1",
  "doc": "Execute script content",
  "fields": [
    { "name": "name", "type": "string", "doc": "Name of the script" },
    { "name": "script", "type": "string", "doc": "Script content to execute" },
    { "name": "scope", "type": "string", "doc": "Scope of execution" },
    { "name": "scope_id", "type": "string", "doc": "Scope identifier" },
    { "name": "scope_name", "type": "string", "doc": "Name of scope" }
  ]
}