{
  "namespace": "xtype.deployment.state.event.external.v1",
  "type": "record",
  "name": "ReleaseExecutionFinishedOkEventV1",
  "fields": [
    {
      "name": "release",
      "type": "xtype.deployment.state.event.external.v1.ReleaseHeaderV1"
    },
    {
      "name": "execution",
      "type": "xtype.deployment.state.event.external.v1.ReleaseExecutionHeaderV1"
    },
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "ended_at",
      "type": "long",
      "doc": "Timestamp when release has ended at"
    }
  ]
}
