version: "3.7"
services:
  foobar-service-manual-dockerfile:
    build:
      context: .
      dockerfile: foobar-service-repacked-agent-and-ext.Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-infrastructure:4318
    ports:
      - "8080:8080"
    depends_on:
      - otel-infrastructure

  foobar-service-layered-jar:
    build:
      context: .
      dockerfile: foobar-service-layered-jar.Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-infrastructure:4318
    ports:
      - "8080:8080"
    depends_on:
      - otel-infrastructure

  otel-infrastructure:
    image: grafana/otel-lgtm:latest
    ports:
      - "51423:3000"
      - "4317:4317" # OpenTelemetry Collector gRPC default port
      - "4318:4318" # OpenTelemetry Collector HTTP default port
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
#      - ./docker/otel-lgtm/run-otelcol.sh:/otel-lgtm/run-otelcol.sh
      - ./docker/otel-lgtm/otelcol-config.yaml:/otel-lgtm/otelcol-config.yaml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:13133/ready" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

