{
  "namespace": "xtype.xus_legacy.v1.data",
  "type": "record",
  "name": "XusRecalculationEventV1",
  "doc": "This payload can be sent to trigger recalculation of all XUS for a given snowCompanyId. No additional fields required, base is sufficient.",
  "fields": [
    {
      "name": "statisticsConsiderAllXus",
      "type": "boolean",
      "doc": "If this flag is set, statistics recalculation should consider all existing XUS for the given customer.",
      "default": false
    },
    {
      "name": "statisticsConsiderAllXusWindow",
      "type": "int",
      "doc": "Limits the number of XUS we need to recalculate statistics for by providing a limit of how many hours we want to go back. -1 signals no limit. This field is only relevant if considerAllXus is set to true.",
      "default": 6
    },
    {
      "name": "table",
      "type": ["null", "string"],
      "default": null,
      "doc": "The snow table name"
    },
    {
        "name": "sysIds",
        "type": [
          "null",
          {
            "type": "array",
            "items": "string"
          }
        ],
        "default": null,
        "doc": "Unique id's of the records in Service Now. Uniqueness in only guaranteed within a single instance, thus not globally unique."
    }
  ]
}
