<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.xtype.api</groupId>
    <artifactId>api</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>avro-api</artifactId>
  <name>Avro API</name>

  <properties>
    <avro-spec-base-dir>${project.basedir}/../../contracts/avro</avro-spec-base-dir>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.avro</groupId>
      <artifactId>avro</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.avro</groupId>
        <artifactId>avro-maven-plugin</artifactId>
        <configuration>
          <sourceDirectory>${avro-spec-base-dir}</sourceDirectory>
          <outputDirectory>${project.build.directory}/generated-sources/avro</outputDirectory>
          <imports>
            <!-- COMMON ACROSS ALL CONTEXTS -->
            <import>${avro-spec-base-dir}/xtype/common/base.avsc</import>
            <import>${avro-spec-base-dir}/xtype/common/user.avsc</import>
            <import>${avro-spec-base-dir}/xtype/common/audit_context.avsc</import>

            <!-- SERVICE: INGESTION/SNOW-DATA -->
            <import>${avro-spec-base-dir}/xtype/snow_data-event-internal/v1/data/data_prepared_event.avsc</import>
            <import>${avro-spec-base-dir}/xtype/snow_data-event-internal/v1/data/data_upload_cancelled_event.avsc</import>
            <import>${avro-spec-base-dir}/xtype/snow_data-event-internal/v1/data/data_upload_completed_event.avsc</import>
            <import>${avro-spec-base-dir}/xtype/snow_data-event-internal/v1/data/data_upload_failed_event.avsc</import>
            <import>${avro-spec-base-dir}/xtype/snow_data-event-internal/v1/data/data_uploaded_event.avsc</import>

            <!-- SERVICE: package-service -->
            <import>${avro-spec-base-dir}/xtype/package/v1/data/deploy_package_event.avsc</import>

            <!-- SERVICE: audit-trail-service -->
            <import>${avro-spec-base-dir}/xtype/audit/v1/data/audit_event.avsc</import>

          </imports>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>schema</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
