logging:
  level:
    io.xtype: DEBUG
spring:
  application:
    name: PackageService
  kafka:
    properties:
      schema:
        registry:
          url: http://127.0.0.1:8081
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
      derive.type: true
    producer:
      client-id: package-service-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1 # Ensures message order
        auto.register.schemas: true
        use.latest.version: true
        max.request.size: 4194304
    bootstrap-servers: 127.0.0.1:9092
server:
  port: 8080