{
  "namespace": "xtype.snow_sync.snow_record_legacy.event.internal.v1",
  "type": "record",
  "name": "MessageV1",
  "fields": [
    {
      "name": "base",
      "type": "xtype.common.Base"
    },
    {
      "name": "snowTable",
      "type": "string",
      "doc": "The original name of the table in the service now."
    },
    {
      "name": "items",
      "type": {
        "type": "array",
        "items": [
          "xtype.snow_sync.snow_record_legacy.event.internal.v1.data.SnowRecordLegacyEventV1",
          "xtype.snow_sync.snow_record_legacy.event.internal.v1.data.SnowRecordLegacyDeletionEventV1"
        ]
      }
    }
  ]
}