{
  "namespace": "xtype.snow_sync.snow_record_legacy.event.internal.v1.data",
  "type": "record",
  "name": "SnowRecordLegacyEventV1",
  "fields": [
    {
      "name": "uid",
      "type": "string",
      "doc": "Unique ID of the record."
    },
    {
      "name": "sysId",
      "type": "string",
      "doc": "The unique id of the record in Service Now. Uniqueness in only guaranteed within a single instance, thus not globally unique."
    },
    {
      "name": "md5",
      "type": "string",
      "doc": "The md5 hash of the content in field 'payload'."
    },
    {
      "name": "logicalGroupId",
      "type": "string",
      "doc": "The unique id of the logical group that was used to upload this record."
    },
    {
      "name": "sysCreatedBy",
      "type": "string",
      "doc": "The creator of this record in ServiceNow."
    },
    {
      "name": "sysCreatedOn",
      "type": "long",
      "doc": "The creation time in ServiceNow (TZ is implicitly in UTC)."
    },
    {
      "name": "sysUpdatedBy",
      "type": ["null", "string"],
      "default": null,
      "doc": "The last updater of this record in ServiceNow."
    },
    {
      "name": "sysUpdatedOn",
      "type": [ "null", "long" ],
      "default": null,
      "doc": "the last update timestamp in ServiceNow (TZ is implicitly in UTC)."
    },
    {
      "name": "payload",
      "type": "string",
      "doc": "The SN record, serialized as JSON."
    }
  ]
}