{
  "namespace": "xtype.snow_sync.snow_record_app.event.external.v1.data",
  "type": "record",
  "name": "SnowRecordAppEventV1",
  "fields": [
    {
      "name": "name",
      "type": ["null", "string"],
      "default": null,
      "doc": "The name of the application, ie. 'xtype''"
    },
    {
      "name": "shortDescription",
      "type": ["null", "string"],
      "default": null,
      "doc": "A short description for the app, ie 'Makes my life better every day!'"
    },
    {
      "name": "active",
      "type": "int",
      "default": 1,
      "doc": "If this app is active or not"
    },
    {
      "name": "version",
      "type": ["null", "string"],
      "default": null,
      "doc": "The version of the ie. '2.0.8'. Might not be present."
    },
    {
      "name": "source",
      "type": ["string"]
    },
    {
      "name": "storeUrl",
      "type": ["null", "string"],
      "default": null,
      "doc": "In case this app is a store app ie. 'https://tpp.servicenow.com/sn_appstore_s'"
    },
    {
      "name": "vendor",
      "type": ["null", "string"],
      "default": null,
      "doc": "The vendor of the app ie. 'ServiceNow'"
    },
    {
      "name": "scope",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "sysModCount",
      "type": "int",
      "default": 0
    }
  ]
}
