{
  "type": "record",
  "name": "NotificationCreated",
  "namespace": "xtype.notifications.notification.event.external.v1",
  "doc": "Obsolete, use NotificationCreatedV1 instead",
  "fields": [
    { "name": "notification_id", "type": "string" },
    { "name": "snow_company_id", "type": "string" },
    { "name": "timestamp", "type": { "type": "long", "logicalType": "timestamp-millis" } },
    {
      "name": "mail_notification",
      "type": ["null", "xtype.notifications.notification.event.external.v1.MailNotification"],
      "default": null
    },
    {
      "name": "ms_teams_notification",
      "type": ["null", "xtype.notifications.notification.event.external.v1.MSTeamsNotification"],
      "default": null
    },
    {
      "name": "slack_notification",
      "type": ["null", "xtype.notifications.notification.event.external.v1.SlackNotification"],
      "default": null
    }
  ]
}
