### Deploy a package
POST http://localhost:8080/packages/deploy
Content-Type: application/json

{
  "packageId": "e1f3bd6c-52d6-45ab-81f4-dc50e6587755",
  "packageName": "A package",
  "triggeredBy": "Foobar",
  "content": [
    {
      "uid": "3c54fc30-5b78-4d1d-b7a3-707d1314934c",
      "type": "update_set",
      "name": "Update Set 1"
    },
    {
      "uid": "d2575235-ec7c-40f3-93c2-4ffed37da904",
      "type": "update_set",
      "name": "Update Set 2"
    }
  ]
}
