{
  "namespace": "xtype.ingestion.snow_record_header.event.internal.v1.data",
  "type": "record",
  "name": "StartDiffingProcessEventV1",
  "fields": [
    {
      "name": "usePartitionHint",
      "type": [ "null", "string" ],
      "default": null,
      "doc": "The partition hint that should be used for diffing, serialized as JSON. Partition hints are usually only sent for records of bigger tables."
    },
    {
      "name": "chunkSize",
      "type": "int",
      "doc": "When using partitioned processing, this property defines how big the chunks should be.",
      "default": 10000
    }
  ]
}