{
  "namespace": "xtype.snow_sync.snow_record_property.event.external.v1.data",
  "type": "record",
  "name": "SnowRecordPropertyEventV1",
  "fields": [
    {
      "name": "description",
      "type": ["null", "string"],
      "default": null,
      "doc": "Provides brief explanation or details about what the system property is used for ie. 'Page header caption'"
    },
    {
      "name": "name",
      "type": ["string"],
      "doc": "This field stores the unique identifier or key for the system property ie. 'glide.product.description'"
    },
    {
      "name": "value",
      "type": ["null", "string"],
      "default": null,
      "doc": "This field stores the value associated with the system property identified by name ie. 'xtype DEV header caption'"
    },
    {
      "name": "sysModCount",
      "type": "int",
      "default": 0
    }
  ]
}