{
  "namespace": "xtype.deployment.state.event.external.v1",
  "type": "record",
  "name": "UpdateSetDeploymentFailedV1",
  "fields": [
    {
      "name": "workflow_execution",
      "type": "xtype.deployment.state.event.external.v1.WorkflowExecutionHeaderV1"
    },
    {
      "name": "task_execution",
      "type": ["null", "xtype.deployment.state.event.external.v1.TaskExecutionHeaderV1"],
      "default": null
    },
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "xus",
      "type": "xtype.deployment.state.event.external.v1.XusHeaderV1"
    },
    {
      "name": "otherProblem",
      "type": "xtype.deployment.state.event.external.v1.OtherProblemV1"
    }
  ]
}
