{
  "namespace": "xtype.snow_sync.snow_record_update_set_source.event.external.v1",
  "type": "record",
  "name": "MessageV1",
  "fields": [
    {
      "name": "base",
      "type": "xtype.common.Base"
    },
    {
      "name": "snowBase",
      "type": "xtype.snow_sync.common.SnowBase"
    },
    {
      "name": "payload",
      "type": [
        "xtype.snow_sync.snow_record_update_set_source.event.external.v1.data.SnowRecordUpdateSetSourceEventV1",
        "xtype.snow_sync.common.SnowDeletionEventV1"
      ]
    }
  ]
}