{
  "namespace": "xtype.ingestion.snow_record_header.event.internal.v1",
  "type": "record",
  "name": "MessageV1",
  "fields": [
    {
      "name": "base",
      "type": "xtype.common.Base"
    },
    {
      "name": "snowTable",
      "type": "string",
      "doc": "The original name of the table in the service now."
    },
    {
      "name": "logicalGroupId",
      "type": [ "long" ],
      "doc": "The unique id of the logical group that was used to upload this record. For historical reason this has to be a sequential number.",
      "default": 0
    },
    {
      "name": "logicalGroupCreationTm",
      "type": [ "long" ],
      "doc": "The timestamp the logical group has been created on. Can be used for database partitioning purposes.",
      "default": 0
    },
    {
      "name": "items",
      "type": {
        "type": "array",
        "items": [
          "xtype.ingestion.snow_record_header.event.internal.v1.data.RequestLogicalGroupCreationEventV1",
          "xtype.ingestion.snow_record_header.event.internal.v1.data.HeaderUploadEventV1",
          "xtype.ingestion.snow_record_header.event.internal.v1.data.StartDiffingProcessEventV1",
          "xtype.ingestion.snow_record_header.event.internal.v1.data.RequestLogicalGroupDeletionEventV1"
        ]
      }
    }
  ]
}