{
  "namespace": "xtype.deployment.state.event.external.v1",
  "type": "record",
  "name": "ReleasePackageDeploymentFailedV1",
  "fields": [
    {
      "name": "workflow_execution",
      "type": "xtype.deployment.state.event.external.v1.WorkflowExecutionHeaderV1"
    },
    {
      "name": "timestamp",
      "type": "long",
      "doc": "Timestamp when event was created"
    },
    {
      "name": "ended_at",
      "type": ["null", "long"],
      "default": null,
      "doc": "Timestamp when package deployment failed at. If null use timestamp field."
    },
    {
      "name": "release_package",
      "type": "xtype.deployment.state.event.external.v1.ReleasePackageHeaderV1"
    }
  ]
}
