{
  "namespace": "xtype.deployment.state.event.external.v1",
  "type": "record",
  "name": "ReleasePackageDeploymentFinishedOkEventV1",
  "fields": [
    {
      "name": "workflow_execution",
      "type": "xtype.deployment.state.event.external.v1.WorkflowExecutionHeaderV1"
    },
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "ended_at",
      "type": "long",
      "doc": "Timestamp when package deployment has ended at"
    },
    {
      "name": "release_package",
      "type": "xtype.deployment.state.event.external.v1.ReleasePackageHeaderV1"
    }
  ]
}
