{
  "namespace": "xtype.deployment.state.event.external.v1",
  "type": "record",
  "name": "ReleasePackageDeploymentStartedEventV1",
  "fields": [
    {
      "name": "workflow_execution",
      "type": "xtype.deployment.state.event.external.v1.WorkflowExecutionHeaderV1"
    },
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "source_instance",
      "type": "string"
    },
    {
      "name": "target_instance",
      "type": "string"
    },
    {
      "name": "executed_by_display_name",
      "type": ["null", "string"],
      "default": null,
      "doc": "Display name of the user who executed the package"
    },
    {
      "name": "executed_by_technical_name",
      "type": ["null", "string"],
      "default": null,
      "doc": "Technical name of the user who executed the package"
    },
    {
      "name": "started_at",
      "type": "long",
      "doc": "Timestamp when package deployment was started at"
    },
    {
      "name": "release_package",
      "type": "xtype.deployment.state.event.external.v1.ReleasePackageHeaderV1"
    }
  ]
}