{
  "namespace": "xtype.snow_sync.snow_record_xus.event.external.v1.data",
  "type": "record",
  "name": "SnowRecordUpdateSetEventV1",
  "fields": [
    {
      "name": "usRusBase",
      "type": "xtype.snow_sync.snow_record_xus.event.external.v1.data.UsRusBaseV1",
      "doc": "Fields common to an UpdateSet and RemoteUpdateSet"
    },
    {
      "name": "remoteSysId",
      "type": ["null", "string"],
      "doc": "An optional reference to the RemoteUpdateSet on the same instance.",
      "default": null
    },
    {
      "name": "completedBy",
      "type": ["null", "string"],
      "doc": "An optional reference to the actor sys_id that completed the UpdateSet ie. 'dfbfca331bb40610639286a7624bcb98'",
      "default": null
    },
    {
      "name": "completedByUserName",
      "type": ["null", "string"],
      "doc": "An optional reference to the actor user name that completed the UpdateSet ie. 'smoke_bot'",
      "default": null
    },
    {
      "name": "completedByUser",
      "type": ["null", "string"],
      "doc": "An optional reference to the actor readable user name that completed the UpdateSet ie. 'Smoke Bot'",
      "default": null
    },
    {
      "name": "completedOn",
      "type": ["null", "long"],
      "doc": "The optional completion time in ServiceNow (TZ is implicitly in UTC).",
      "default": null
    },
    {
      "name": "baseUpdateSet",
      "type": ["null", "string"],
      "doc": "An optional reference to the top level UpdateSet.",
      "default": null
    },
    {
      "name": "parent",
      "type": ["null", "string"],
      "doc": "An optional reference to the parent.",
      "default": null
    },
    {
      "name": "xContentApps",
      "type": {
        "type": "map",
        "values": "int"
      },
      "doc": "Contains a reference to all Scopes that are referenced by Files in this UpdateSet. For each Scope, the number of Files is given."
    },
    {
      "name": "xCommitLogs",
      "type": ["null", "xtype.snow_sync.snow_record_xus.event.external.v1.data.XCommitLogsV1"],
      "doc": "Optional commit logs of a UpdateSet",
      "default": null
    }
  ]
}