{
  "namespace": "xtype.snow_sync.snow_record_xus.event.external.v1.data",
  "type": "record",
  "name": "XCommitLogsV1",
  "fields": [
    {
      "name": "infoLogs",
      "type": "int",
      "doc": "Number of info logs"
    },
    {
      "name": "errorLogs",
      "type": "int",
      "doc": "Number of error logs"
    },
    {
      "name": "warningLogs",
      "type": "int",
      "doc": "Number of warning logs"
    },
    {
      "name": "finishedLogFound",
      "type": "boolean",
      "doc": "Finished log was found"
    }
  ]
}